services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_OPTIONS: ${NODE_OPTIONS:-"--max-old-space-size=512"}
    environment:
      NITRO_HOST: ${NITRO_HOST:-0.0.0.0}
      NITRO_PORT: ${NITRO_PORT:-3000}
      NODE_OPTIONS: ${NODE_OPTIONS:-"--max-old-space-size=512"}
    ports:
      - "${HOST_PORT:-3000}:3000"
    restart: unless-stopped
